-- Supabase ve PostGIS Veritabanı Şeması Kurulum Script'i
-- iNaturalist-Lite Projesi
-- Lütfen bu script'i doğrudan Supabase SQL Editor'da çalıştırınız.

-- 1. PostGIS Uzantısını Etkinleştir (Mekansal Veri Desteği İçin)
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE plant_comments (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    plant_id integer NOT NULL,
    username text NOT NULL,
    text text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_plant_comments" PRIMARY KEY (id)
);

CREATE TABLE plant_likes (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    plant_id integer NOT NULL,
    username text NOT NULL,
    CONSTRAINT "PK_plant_likes" PRIMARY KEY (id)
);

CREATE TABLE plants (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    description text,
    photourl text,
    createdat timestamp with time zone NOT NULL,
    username text NOT NULL,
    userbadge text NOT NULL,
    location geometry,
    CONSTRAINT "PK_plants" PRIMARY KEY (id)
);

CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    username text NOT NULL,
    email text NOT NULL,
    password_hash text NOT NULL,
    badge text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    otp_code text,
    otp_expiry timestamp with time zone,
    avatar_url text,
    CONSTRAINT "PK_users" PRIMARY KEY (id)
);

CREATE UNIQUE INDEX "IX_plant_likes_plant_id_username" ON plant_likes (plant_id, username);

CREATE UNIQUE INDEX "IX_users_email" ON users (email);

CREATE UNIQUE INDEX "IX_users_username" ON users (username);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260608120842_AddAuthFields', '10.0.0');

COMMIT;

START TRANSACTION;
CREATE INDEX "IX_plant_comments_plant_id" ON plant_comments (plant_id);

ALTER TABLE plant_comments ADD CONSTRAINT "FK_plant_comments_plants_plant_id" FOREIGN KEY (plant_id) REFERENCES plants (id) ON DELETE CASCADE;

ALTER TABLE plant_likes ADD CONSTRAINT "FK_plant_likes_plants_plant_id" FOREIGN KEY (plant_id) REFERENCES plants (id) ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260609144630_AddCascadeDelete', '10.0.0');

COMMIT;

